"""
Core functionality for passive voice detection.
"""

from .patterns import (
    PASSIVE_PATTERNS,
    PASSIVE_EXPRESSIONS,
    NON_PASSIVE_COMBOS,
    PERSONAL_MENTAL_STATES,
    ADJECTIVAL_PARTICIPLES,
    COMMON_PASSIVE_PATTERNS,
    SPECIAL_PASSIVE_PATTERNS,
    FALSE_POSITIVE_PATTERNS,
    COMMON_PASSIVE_VERBS,
    CONFIDENCE_SCORES
)

__all__ = [
    'PASSIVE_PATTERNS',
    'PASSIVE_EXPRESSIONS',
    'NON_PASSIVE_COMBOS',
    'PERSONAL_MENTAL_STATES',
    'ADJECTIVAL_PARTICIPLES',
    'COMMON_PASSIVE_PATTERNS',
    'SPECIAL_PASSIVE_PATTERNS',
    'FALSE_POSITIVE_PATTERNS',
    'COMMON_PASSIVE_VERBS',
    'CONFIDENCE_SCORES'
] 